<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Bien;

/**
 * BienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BienRepository extends \Doctrine\ORM\EntityRepository
{

	public function countBien()
	{
		$qb = $this->_em->createQueryBuilder();

		$qb->select('COUNT(b)')
			->from(Bien::class, 'b');

		return $qb->getQuery()->getSingleScalarResult();
	}
}
