<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Chantier;
use Doctrine\Common\Cache\ApcuCache;
use Doctrine\ORM\Configuration;
use Doctrine\ORM\Mapping;
use Psr\SimpleCache\CacheInterface;

/**
 * ChantierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChantierRepository extends \Doctrine\ORM\EntityRepository
{
	CONST MAX_RESULT = 4;

	public function findAllFromCache()
	{
		$qb = $this->getEntityManager()->createQuery(
			'SELECT c FROM AppBundle:chantier c'
		);
		$qb->useResultCache(true, 3600, 'liste_chantier_cache');

		return $qb->getResult();
	}


	public function nombreChantiers()
	{
		$qb = $this->getEntityManager()->createQuery(
			'SELECT COUNT(c) FROM AppBundle:Chantier c'
		);

		$qb->useResultCache(true, 3600, 'nombre_chantiers_cache');
		return $qb->getResult();
	}

	public function quattreChantierPlusAvancer()
	{
		$qb = $this->getEntityManager()->createQuery(
			'SELECT c FROM AppBundle:Chantier c 
				  ORDER BY c.pourcentage DESC'
		)->setMaxResults(self::MAX_RESULT);

		$qb->useResultCache(true, 3600, 'quattre_chantier_plus_avancer_cache');
		return $qb->getResult();
	}

}
