<?php

namespace AppBundle\Repository;

/**
 * ColorisParquetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColorisParquetRepository extends \Doctrine\ORM\EntityRepository
{
}
