<?php

namespace AppBundle\Repository;

/**
 * CommentaireChantierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireChantierRepository extends \Doctrine\ORM\EntityRepository
{
}
