<?php

namespace AppBundle\Repository;

/**
 * SupplementParquetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplementParquetRepository extends \Doctrine\ORM\EntityRepository
{



}
