<?php

namespace AppBundle\Repository;

/**
 * SupplementTerrasseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplementTerrasseRepository extends \Doctrine\ORM\EntityRepository
{
}
