<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

	public function getUserByRole()
	{
		$qb = $this->_em->createQueryBuilder();
		$qb->select('u')
			->from(User::class, 'u')
			->where('u.roles LIKE :roles OR u.roles LIKE :roles2')
			->andWhere('u.enabled = :enabled')
			->setParameter('roles', '%"ROLE_CHEF"%')
			->setParameter('roles2', '%"ROLE_USER"%')
			->setParameter('enabled', true);

		return $qb->getQuery()->getResult();
	}

	public function nombreDutilisateur()
	{
		$qb = $this->_em->createQueryBuilder();
		$qb->select('COUNT(u)')
			->from(User::class, 'u');

		return $qb->getQuery()->getSingleScalarResult();
	}

}
