app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user_login:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_change_password:
    path: /change-password
    controller: AppBundle:ChangePassword:changePassword
