<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIipo0tf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIipo0tf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIipo0tf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIipo0tf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIipo0tf\appDevDebugProjectContainer([
    'container.build_hash' => 'Iipo0tf',
    'container.build_id' => 'd66f00da',
    'container.build_time' => 1567267501,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIipo0tf');
