<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7mti61y\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7mti61y/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container7mti61y.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container7mti61y\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container7mti61y\appDevDebugProjectContainer([
    'container.build_hash' => '7mti61y',
    'container.build_id' => '5c41975a',
    'container.build_time' => 1567540724,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7mti61y');
