<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ99t7bv\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ99t7bv/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZ99t7bv.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZ99t7bv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZ99t7bv\appDevDebugProjectContainer([
    'container.build_hash' => 'Z99t7bv',
    'container.build_id' => 'a3f8e67f',
    'container.build_time' => 1567612680,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ99t7bv');
